### ISSUE TITLE
Correction required in setting environment variable (Step 2)

### ISSUE THREAD

**Issue by SystemicEmotions** [aws-samples/amazon-eks-cdk-blue-green-cicd#3]
The command provided to set the INSTANCE_ROLE in environment variable needs corrections as it is not retrieving the instance role from cloudFormation created resources list and hence leading to failure of ingress pod. 

Currently the command mentioned is 
INSTANCE_ROLE=$(aws cloudformation describe-stack-resources --stack-name CdkStackALBEksBg | jq .StackResources[].PhysicalResourceId | grep CdkStackALBEksBg-ClusterDefaultCapacityInstanceRol | tr -d '["\r\n]')

Correct one to point to logical
INSTANCE_ROLE=$(aws cloudformation describe-stack-resources --stack-name CdkStackALBEksBg | jq .StackResources[].PhysicalResourceId | grep CdkStackALBEksBg-ClusterNodegroupDefaultCapacityNo | tr -d '["\r\n]')

**Comment by nvaidya1** [comment]
@SystemicEmotions, thank you for bringing it to attn. With newer version of CDK, the ASG is replaced with NodeGroup, Roles renamed and Security group behavior changed. If we can freeze the CDK version to not the latest one, we will get the expected behavior. I have updated the instruction and package.json file to accurately represent the CDK version and verified by testing it.
Please let me know if you see any further discrepancies.
I am closing this case, however, if you see an issue, please feel free to re-open. Thanks for your time.
